core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('mentorados/', include('mentorados.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentorados/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MentoradosView.as_view(), name='mentorados'),
    path('reunioes/', views.ReunioesView.as_view(), name='reunioes'),
    path('auth/', views.AuthView.as_view(), name="auth_mentorado"),
    path('escolher_dia/', views.EscolherDiaView.as_view(), name='escolher_dia'),
    path('agendar_reuniao/', views.AgendarReuniao.as_view(), name='agendar_reuniao'),
    path('tarefa/<int:id>', views.TarefasView.as_view(), name='tarefa'),
    path('upload/<int:id>', views.UploadView.as_view(), name='upload'),
    path('tarefa_mentorado/', views.TarefaMentoradoView.as_view(), name='tarefa_mentorado'),
    path('tarefa_alterar/<int:id>', views.TarefaAlterarView.as_view(), name="tarefa_alterar")
]

mentorados/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import timedelta
import secrets 
from datetime import time

class Navigators(models.Model):
    nome = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
    
    class Meta:
        db_table = 'navigators'
        verbose_name = 'navigators'
        verbose_name_plural = 'navigators'

class Estagios(models.TextChoices):
    E1 = 'E1', '10-100K'
    E2 = 'E2', '101-500K'
    E3 = 'E3', '501-1M'

class Mentorados(models.Model):
    nome = models.CharField(max_length=255)
    foto = models.ImageField(upload_to='fotos', null=True, blank=True)
    estagio = models.CharField(max_length=2, choices=Estagios.choices, default=Estagios.E1)
    navigator = models.ForeignKey(Navigators, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    criado_em = models.DateField(auto_now_add=True)
    token = models.CharField(max_length=16, null=True, blank=True)

    class Meta:
        db_table = 'mentorados'
        verbose_name = 'mentorados'
        verbose_name_plural = 'mentorados'
        
    def __str__(self):
        return self.nome
    
    def gerar_token_unico(self):
        while True:
            token = secrets.token_urlsafe(8)
            if not Mentorados.objects.filter(token=token).exists():
                return token

    def save(self, *args, **kwargs):
        # adição do token de autenticação
        if not self.token:
            self.token = self.gerar_token_unico()
        return super().save(*args, **kwargs)
    
# Reuniões
    
class DisponibilidadeHorarios(models.Model):
    data_inicial = models.DateTimeField(null=True, blank=True)
    mentor = models.ForeignKey(User, on_delete=models.CASCADE)
    agendado = models.BooleanField(default=False)

    @property
    def data_final(self):
        return self.data_inicial + timedelta(minutes=50)
    
    class Meta:
        db_table = 'horarios'
        verbose_name = 'horarios'
        verbose_name_plural = 'horarios'
    
    def __str__(self):
        return f'{self.data_inicial.time()} às {self.data_final.time()}'

class Tag(models.TextChoices):
    G = 'G', 'Gestão'
    M = 'M', 'Marketing'
    RH = 'RH', 'Gestão de pessoas'
    I = 'I', 'Impostos'
    
class Reuniao(models.Model):
    data = models.ForeignKey(DisponibilidadeHorarios, on_delete=models.CASCADE)
    mentorado = models.ForeignKey(Mentorados, on_delete=models.CASCADE)
    tag = models.CharField(max_length=2, choices=Tag.choices, default=Tag.G)
    descricao = models.TextField()

    class Meta:
        db_table = 'reunioes'
        verbose_name = 'reunioes'
        verbose_name_plural = 'reunioes'

    def __str__(self):
        return f'{self.mentorado} - {self.data}'

class Tarefa(models.Model):
    mentorado = models.ForeignKey(Mentorados, on_delete=models.DO_NOTHING)
    tarefa = models.CharField(max_length=255)
    realizada = models.BooleanField(default=False)

    class Meta:
        db_table = 'tarefas'
        verbose_name = 'tarefa'
        verbose_name_plural = 'tarefas'

class Upload(models.Model):
    mentorado = models.ForeignKey(Mentorados, on_delete=models.DO_NOTHING)
    video = models.FileField(upload_to='video')

    class Meta:
        db_table = 'upload'
        verbose_name = 'upload'
        verbose_name_plural = 'uploads'

mentorados/views.py
from django.views import generic, View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Mentorados, Estagios, DisponibilidadeHorarios, Reuniao, Tarefa, Upload
from .forms import MentoradosCadastroForm, DisponibilidadeHorarioForm, AuthMentoradoForm, ReuniaoForm, TarefaForm, UploadsForm
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from .auth import valida_token
from json import loads
from datetime import datetime
from django.utils.timezone import timedelta
from django.http import Http404
from django.utils.decorators import method_decorator

class MentoradosView(LoginRequiredMixin, generic.CreateView):
    model = Mentorados
    form_class = MentoradosCadastroForm
    template_name = 'mentorados.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.constants.SUCCESS, 'Mentorado cadastrado com sucesso.')
        return reverse('mentorados')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_context_data(self, **kwargs):
        # Contexto mentorados
        mentorados = Mentorados.objects.filter(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['mentorados'] = mentorados

        # Contexto estágio
        estagios = [estagio[1] for estagio in Estagios.choices]
        qtd_estagio = []
        for i, j in Estagios.choices:
            x = Mentorados.objects.filter(estagio=i).filter(user=self.request.user).count()
            qtd_estagio.append(x)

        context['grafico'] = {
            'estagios': estagios,
            'qtd_estagio': qtd_estagio
        }

        return context
        
class ReunioesView(LoginRequiredMixin, generic.CreateView):
    model = DisponibilidadeHorarios
    form_class = DisponibilidadeHorarioForm
    template_name = 'reunioes.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reunioes = Reuniao.objects.filter(data__mentor=self.request.user)
        context['reunioes'] = reunioes
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''
        for k, v in errors.items():
            for valor in v:
                erro_msg = valor['message']
        
        if erro_msg:
            messages.error(self.request, erro_msg)
        return super().form_invalid(form)
    
    def get_success_url(self):
        messages.add_message(self.request, messages.constants.SUCCESS, 'Horario disponibilizado com sucesso.')
        return reverse('reunioes')
    
class AuthView(generic.FormView):
    form_class = AuthMentoradoForm
    template_name = 'auth_mentorado.html'

    def get_success_url(self):
        messages.success(self.request, 'Autenticação realizada com sucesso.')
        return reverse('escolher_dia')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        response.set_cookie('auth_token', form.cleaned_data.get('token'), max_age=3600)
        return response

    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''
        for k, v in errors.items():
            for valor in v:
                erro_msg = valor['message']
        
        if erro_msg:
            messages.error(self.request, erro_msg)
        return super().form_invalid(form)
    
class EscolherDiaView(generic.TemplateView):
    template_name = 'escolher_dia.html'

    def get(self, request, *args, **kwargs):
        if not valida_token(request.COOKIES.get('auth_token')):
            return redirect('auth_mentorado')
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        if not valida_token(request.COOKIES.get('auth_token')):
            return redirect('auth_mentorado')
        return super().post(request, *args, **kwargs)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Horarios
        mentorado =  valida_token(self.request.COOKIES.get('auth_token'))
        disponibilidades = DisponibilidadeHorarios.objects.filter(
            data_inicial__gte=datetime.now(),
            agendado=False,
            mentor=mentorado.user
        ).values_list('data_inicial', flat=True)
        datas = [i.date() for i in disponibilidades]
        context['datas'] = list(set(datas))

        return context
    
class AgendarReuniao(generic.CreateView):
    model = Reuniao
    form_class = ReuniaoForm
    template_name = 'agendar_reuniao.html'

    def get(self, request, *args, **kwargs):
        if not valida_token(request.COOKIES.get('auth_token')):
            return redirect('auth_mentorado')
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        if not valida_token(request.COOKIES.get('auth_token')):
            return redirect('auth_mentorado')
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['mentorado'] = valida_token(self.request.COOKIES.get('auth_token'))
        return kwargs
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        if self.request.method == 'GET' and self.request.GET.get('data'):
            mentorado = valida_token(self.request.COOKIES.get('auth_token'))
            data = datetime.strptime(self.request.GET.get('data'), '%d-%m-%Y')
            horarios = DisponibilidadeHorarios.objects.filter(
                data_inicial__gte=data,
                data_inicial__lt=data + timedelta(days=1),
                agendado=False,
                mentor=mentorado.user
            )
            if horarios:
                form.fields['data'].initial = horarios[0]
            form.fields['data'].queryset = horarios

        return form
    
    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''
        for k, v in errors.items():
            for valor in v:
                erro_msg = valor['message']
        
        if erro_msg:
            messages.error(self.request, erro_msg)
            print(erro_msg)
        return super().form_invalid(form)
    
    def get_success_url(self):
        messages.add_message(self.request, messages.constants.SUCCESS, 'Horario agendado com sucesso.')
        return reverse('escolher_dia')
    
class TarefasView(generic.CreateView):
    model = Tarefa
    form_class = TarefaForm
    template_name = 'tarefa.html'
    
    def get_mentorado(self):
        try:
            return Mentorados.objects.get(id=self.kwargs.get('id'))
        except:
            raise Http404

    def get(self, request, *args, **kwargs):
        if self.get_mentorado().user != request.user:
            raise Http404
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        if self.get_mentorado().user != request.user:
            raise Http404
        return super().get(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['mentorado'] = self.get_mentorado()
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mentorado'] = self.get_mentorado()
        context['form2'] = kwargs.get('form2') or UploadsForm()
        context['tarefas'] = Tarefa.objects.filter(mentorado=self.get_mentorado())
        context['videos'] = Upload.objects.filter(mentorado=self.get_mentorado())
        return context
    
    def get_success_url(self):
        return reverse('tarefa', kwargs={'id': self.kwargs.get('id')})

class UploadView(View):
    def get_mentorado(self):
        try:
            return Mentorados.objects.get(id=self.kwargs.get('id'))
        except:
            raise Http404
        
    def get(self, request, *args, **kwargs):
        return redirect(reverse('tarefa', kwargs={'id': self.get_mentorado().id}))
    
    def post(self, request, *args, **kwargs):
        form = UploadsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(self.get_mentorado())
        return redirect(reverse('tarefa', kwargs={'id': self.get_mentorado().id}))

class TarefaMentoradoView(generic.TemplateView):
    template_name = 'tarefa_mentorado.html'

    def get(self, request, *args, **kwargs):
        if not valida_token(request.COOKIES.get('auth_token')):
            return redirect('auth_mentorado')
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        if not valida_token(request.COOKIES.get('auth_token')):
            return redirect('auth_mentorado')
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mentorado'] = valida_token(self.request.COOKIES.get('auth_token'))
        context['videos'] = Upload.objects.filter(mentorado=context.get('mentorado'))
        context['tarefas'] = Tarefa.objects.filter(mentorado=context.get('mentorado'))
        return context

@method_decorator(csrf_exempt, name='dispatch')
class TarefaAlterarView(View):
    def get_mentorado(self):
        try:
            return Mentorados.objects.get(id=self.kwargs.get('id'))
        except:
            raise Http404
        
    def get(self, request, *args, **kwargs):
        return redirect(reverse('tarefa', kwargs={'id': self.get_mentorado().id}))

    def post(self, request, *args, **kwargs):

mentorados/templates/agendar_reuniao.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-5xl mx-auto py-8">
      <form action="{% url 'agendar_reuniao' %}" method="POST">{% csrf_token %}
        <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Agende sua reunião</h2>
        <label for="email" class="block mt-4 text-sm/6 font-medium text-gray-200">Horário</label>
        {{form.data}}
        <label for="email" class="block mt-4 text-sm/6 font-medium text-gray-200">Tag</label>
        {{form.tag}}
        <label for="email" class="block mt-4 text-sm/6 font-medium text-gray-200">Descrição</label>
        {{form.descricao}}
        <button type="submit" class="flex mt-4 w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Agendar</button>
      </form>   
    </div>
  </div>

  
{% endblock 'body' %}

mentorados/templates/auth_mentorado.html
{% extends "base.html" %}

{% block 'body' %}
    <div class="bg-gray-900 flex items-center justify-center h-screen">
        <div class="bg-gray-800 p-8 rounded-lg shadow-lg text-center w-96">
            <form action="{% url 'auth_mentorado' %}" method="POST"> 
                {% csrf_token %}
                <h2 class="text-2xl font-bold text-gray-200 mb-4">Acessar conteúdo</h2>
                {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <label class="text-gray-400 block text-left mb-1">Token de acesso</label>
                {{form.token}}
                <button class="w-full mt-4 bg-indigo-600 text-white font-semibold p-3 rounded-md hover:bg-indigo-700 transition cursor-pointer">Acessar</button>
            </form>
        </div>
    </div>
{% endblock 'body' %}

mentorados/templates/escolher_dia.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto py-8">
        <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Escolha o dia para reunião</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="rounded-md {{message.tags}} mt-4">
                    <div class="flex">
                        <div class="ml-3 py-4">
                            {{message}}

                        </div>

                    </div>
                </div>
            {% endfor %}
        {% endif %}
        <ul role="list" class="mt-3 grid grid-cols-1 gap-5 sm:grid-cols-2 sm:gap-6 lg:grid-cols-4">
            {% for data in datas %}         
                <li class="col-span-1 flex rounded-md shadow-sm">
                   
                        <div class="flex px-4 shrink-0 items-center justify-center rounded-l-md bg-pink-600 text-sm font-medium text-white">{{data|date:"F"}}</div>
                        <div class="flex flex-1 items-center justify-between truncate rounded-r-md border-b border-r border-t border-gray-200 bg-white">
                            <div class="flex-1 truncate px-4 py-2 text-sm">
                            <a href="{% url 'agendar_reuniao' %}?data={{data|date:'d-m-Y'}}" class="font-medium text-gray-900 hover:text-gray-600">{{data|date:"l"}}</a>
                            <p class="text-gray-500">{{data|date:"d-m-Y"}}</p>
                            </div>
                        </div>
                    
                </li>    
            {% endfor %}
            
        </ul>
    </div>
  </div>

  
{% endblock 'body' %}

mentorados/templates/mentorados.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
<header class="bg-slate-900">
    <nav class="flex items-center justify-between p-4 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="{% url 'mentorados' %}" class="text-sm/6 font-semibold text-gray-100">Mentorados</a>
        <a href="{% url 'reunioes' %}" class="text-sm/6 font-semibold text-gray-100">Reunioes</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        
      </div>
    </nav>
    
    </div>
  </header>
  
 
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto py-12">
        <div class="grid grid-cols-2 gap-4">
            <div>
              <form action="{% url 'mentorados' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Cadastre seus mentorados</h2> 
                {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <div>
                    <label for="email" class="block text-sm/6 font-medium text-gray-200">Nome</label>
                    <div class="mt-2">
                        {{form.nome}}
                    </div>
                </div>
                <div class="grid grid-cols-2 gap-4 mt-4">
                    <div>
                        <label class="block text-sm/6 font-medium text-gray-200">Foto</label>
                        <div class="mt-2">
                            {{form.foto}}
                        </div>
                    </div>
                    <div>
                        <label class="block text-sm/6 font-medium text-gray-200">Estágio</label>
                        <div class="mt-2">
                            {{form.estagio}}
                        </div>
                    </div>

                </div>

                <div class="mt-4">
                    <label class="block text-sm/6 font-medium text-gray-200">Navigator</label>
                    <div class="mt-2">
                        {{form.navigator}}
                    </div>
                    <br>
                    <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cadastrar</button>
                </div>
              </form>
            </div>

            <div class="flex justify-center items-center w-1/2 mx-auto">
                <canvas id="myChart" class="w-24 h-24"></canvas>                
            </div>


        </div>
        <div class="mt-6">
            <hr class="border-gray-600">
            <br>    
            <h2 class="text-base/7 font-semibold text-white ">Seus mentorados</h2>
            <table class="mt-6 w-full whitespace-nowrap text-left">
              <colgroup>
                <col class="w-full sm:w-4/12">
                <col class="lg:w-4/12">
                <col class="lg:w-2/12">
                <col class="lg:w-1/12">
                <col class="lg:w-1/12">
              </colgroup>
              <thead class="border-b border-white/10 text-sm/6 text-white">
                <tr>
                  <th scope="col" class="py-2 pl-4 pr-8 font-semibold sm:pl-6 lg:pl-8">Usuário</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold sm:table-cell">Estágio</th>
                  <th scope="col" class="py-2 pl-0 pr-4 text-right font-semibold sm:pr-8 sm:text-left lg:pr-20">Status</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Data entrada</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Navigator</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-white/5">
                
                {% for mentorado in mentorados %}
                  <tr>
                    <td class="py-4 pl-4 pr-8 sm:pl-6 lg:pl-8">
                      <div class="flex items-center gap-x-4">
                        <img src="{{mentorado.foto.url}}" alt="" class="size-8 rounded-full bg-gray-800">
                        <div class="truncate text-sm/6 font-medium text-white"><a href="{% url 'tarefa' mentorado.id %}">{{mentorado.nome}}</a></div>
                      </div>
                    </td>
                    <td class="hidden py-4 pl-0 pr-4 sm:table-cell sm:pr-8">
                      <div class="flex gap-x-3">
                        <div class="rounded-md bg-gray-700/40 px-2 py-1 text-xs font-medium text-gray-400 ring-1 ring-inset ring-white/10">{{mentorado.get_estagio_display}}</div>
                      </div>
                    </td>
                    <td class="py-4 pl-0 pr-4 text-sm/6 sm:pr-8 lg:pr-20">
                      <div class="flex items-center justify-end gap-x-2 sm:justify-start">
                        <div class="flex-none rounded-full bg-green-400/10 p-1 text-green-400">
                          <div class="size-1.5 rounded-full bg-current"></div>
                        </div>
                        <div class="hidden text-white sm:block">Ativo</div>
                      </div>
                    </td>
                    <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">{{mentorado.criado_em}}</td>
                    <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">
                        {{mentorado.navigator}}
                    </td>
                  </tr>
                {% empty %}
                    <tr>
                        <td class="py-4 pl-4 pr-8 sm:pl-6 lg:pl-8 text-sm/6 font-medium text-white" colspan="5">
                            Nenhum mentorado encontrado.
                        </td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

    </div>
     
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'pie',
    data: {
      labels: {{grafico.estagios|safe}},
      datasets: [{
        label: '',
        data: {{grafico.qtd_estagio|safe}},
        borderWidth: 1
      }]
    },
    
  });
</script>
{% endblock 'body' %}

mentorados/templates/reunioes.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
<header class="bg-slate-900">
    <nav class="flex items-center justify-between p-4 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="{% url 'mentorados' %}" class="text-sm/6 font-semibold text-gray-100">Mentorados</a>
        <a href="{% url 'reunioes' %}" class="text-sm/6 font-semibold text-gray-100">Reunioes</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        
      </div>
    </nav>
  </header>
  
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto py-8">
        <div class="grid grid-cols-2 gap-12 ">
            <div>
              {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'reunioes' %}" method="POST">
                    {% csrf_token %}
                    <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Abra um horário</h2>
                    <label for="email" class="block text-sm/6 font-medium text-gray-200">Data</label>
                    {{form.data_inicial}}
                    <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mt-4">Abrir horários</button>
                </form>

            </div>
            <div>
              
                
                <ul role="list" class="divide-y divide-gray-800">
                  {% for reuniao in reunioes %}
                    <li class="flex justify-between gap-x-6 py-5">
                      <div class="flex min-w-0 gap-x-4">
                        <img class="size-12 flex-none rounded-full bg-gray-800" src="{{reuniao.mentorado.foto.url}}" alt="">
                        <div class="min-w-0 flex-auto">
                          <p class="text-sm/6 font-semibold text-white">{{reuniao.mentorado.nome}}</p>
                          <p class="mt-1 truncate text-xs/5 text-gray-400">{{reuniao.descricao}}</p>
                        </div>
                      </div>
                      <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
                        <p class="text-sm/6 text-white">{{reuniao.data.data_inicial}}</p>
                        <p class="mt-1 text-xs/5 text-gray-400">{{reuniao.get_tag_display}}</p>
                      </div>
                    </li>
                  {% endfor %}
                  </ul>
                  
            </div>
        </div>

    </div>
  </div>

{% endblock 'body' %}